apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "oguntescom.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tescom-frontend-srv
                port:
                  number: 3000
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: tescom-backend-srv
                port:
                  number: 8001
  ingressClassName: nginx