apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: backend
spec:
  rules:
    - host: "oguntescom.com"
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: tescom-backend-srv
                port:
                  number: 8001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tescom-frontend-srv
                port:
                  number: 3000
    - host: "oguntescom.gov.ng"  # Add your new domain here
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: tescom-backend-srv
                port:
                  number: 8001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tescom-frontend-srv
                port:
                  number: 3000
  ingressClassName: nginx
